Docker File updates
medic/cht-sync pull request #16
Opened 2022-12-13 04:55 UTC by njogz

- Use an env variable to set `DATAEMON_INITAL_PACKAGE` instead of a hard-coded string
- Add some initialisation scripts for superset

2022-12-13 07:41 UTC, garethbowen requested changes
Nice one! One suggestion...

2022-12-13 07:41 UTC, garethbowen commented on superset/Dockerfile
> +               --password admin
We should probably force users to specify an admin password in their environment variables.

2023-01-16 14:32 UTC, andrablaj commented
@njogz who could help review this PR while Gareth is on vacation, to have things moving forward?

2023-01-19 18:49 UTC, derickl approved these changes
Looks good.

I've left some suggestions inline

2023-01-19 18:49 UTC, derickl commented on README.md
> +CHT_PIPELINE_BRANCH_URL=<The CHT Pipeline  branch to use e.g. https://github.com/medic/cht-pipeline.git#first_release>
Nitpick: would it really be a branch url if we just use the default repo url which defaults to main?

2023-01-19 18:49 UTC, derickl commented on superset/Dockerfile
>  RUN pip install psycopg2-binary
I do not think we need to install the two psycopg2 variants. The former would be used when you need to build it from source while the latter is used when you want a pre-built package https://pypi.org/project/psycopg2-binary/

psycopg2-binary would be appropriate for this scenario.

2023-02-01 22:54 UTC, garethbowen approved these changes
Nice work. Ship it.

2023-02-08 11:54 UTC, merged