fix(#193): only create indexes if table does not exist
medic/cht-sync pull request #194
Opened 2024-12-09 09:33 UTC by witash

closes #193 

check if table exists in a separate query before creating indexes

2024-12-09 13:05 UTC, dianabarsan requested changes
Sweet. One minor change + unit test request.

2024-12-09 13:05 UTC, dianabarsan commented on couch2pg/src/setup.js
> +  const tableExists = await checkTableExists(client);
Can return early here instead: 
```suggestion
if (await checkTableExists(client)) {
  return;
}
```

2024-12-09 13:05 UTC, dianabarsan commented on couch2pg/tests/unit/setup.spec.js
> +    pgClient.query.withArgs(`SELECT 1 FROM v1.whatever LIMIT 1;`).rejects({
Please add a unit test where the table already exists and doesn't get created on startup.

2024-12-10 11:45 UTC, witash commented
looking a bit deeper into postgres locking and there's a simpler way to fix this; using `CREATE INDEX CONCURRENTLY IF NOT EXISTS` acquires a less restrictive lock ('SHARE UPDATE EXCLUSIVE') which doesn't conflict with the type of lock that inserts get ('ROW EXCLUSIVE').

2024-12-10 12:30 UTC, dianabarsan approved these changes
Thanks for spending extra time to read about how locks get triggered in PG! This is absolutely much better!

2024-12-11 08:47 UTC, merged