fixed make prod bug
medic/cht-sync pull request #30
Opened 2023-06-21 18:36 UTC by samuelimoisili

Added a docker compose file to fix `make prod` postgrest startup issue.

Closes #28

2023-06-22 11:59 UTC, andrablaj commented
I managed to reproduce @mrjones-plip's [bug](https://github.com/medic/cht-sync/issues/28) locally on the `main` branch.

If I run `make prod `on this PR's branch (after running CHT locally with the docker helper), I get the following error in the `dbt` container:

> Unable to connect! could not translate host name "postgres" to address: Name or service not known

2023-06-22 19:45 UTC, samuelimoisili commented
@andrablaj You'll to setup a PostgreSQL database and update the following environment variables:

```env
DBT_POSTGRES_HOST=
DBT_POSTGRES_USER=
DBT_POSTGRES_PASSWORD=
POSTGRES_DB=
POSTGRES_TABLE=
DBT_POSTGRES_SCHEMA=
POSTGRES_SCHEMA=
```

2023-06-22 22:13 UTC, mrjones-plip commented
@andrablaj  - I'm waaaay behind on my mail/slack/todo queue - removing myself as a reviewer to unblock.

2023-06-27 14:33 UTC, andrablaj commented
@samuelimoisili, following up here with some items from our 1:1 discussion:

- I didn't see any mention in the documentation about installing PostgreSQL as a prerequisite to run `cht-sync`. Can you please add that step in the `README`?
- You mentioned having a docker-compose file for setting up PostgreSQL locally. Can you please share it in the repo with instructions on how to use it and how it reflects in the` .env` file variables?  

Thanks!

2023-06-28 14:51 UTC, andrablaj requested changes
🎆 Awesome, I managed to run `make prod` successfully locally, with the latest CHT run via docker helper. Great job! 

Nevertheless, the documentation needs updates as I needed to perform extra steps to have this running correctly. 

1. Content of `.env`:

```shell
# project wide: optional
COMPOSE_PROJECT_NAME=pipeline

# postgrest and pogresql: required environment variables for 'gamma', prod and 'local'
POSTGRES_USER=root
POSTGRES_PASSWORD=supercoolpassword
POSTGRES_DB=data
POSTGRES_TABLE=couchdb
POSTGRES_SCHEMA=v1

# dbt: required environment variables for 'gamma', 'prod' and 'local'
DBT_POSTGRES_USER=dbt_user
DBT_POSTGRES_PASSWORD=supercoolpassword
DBT_POSTGRES_SCHEMA=dbt
DBT_POSTGRES_HOST=yourIP
CHT_PIPELINE_BRANCH_URL=https://github.com/medic/cht-pipeline.git#main

# couchdb and logstash: required environment variables for 'gamma', 'prod' and 'local'
COUCHDB_USER=medic
COUCHDB_PASSWORD=password
COUCHDB_DB=medic-users-meta
COUCHDB_HOST=yourCHThost
COUCHDB_PORT=yourCHTport
COUCHDB_SECURE=false

# superset: required environment variables for 'gamma', 'prod' and 'local'
SUPERSET_PASSWORD=password
SUPERSET_ADMIN_EMAIL=user@superset.com
```
2. Run `make prod`
3. Run `docker-compose -f docker-compose.postgres.yml -f docker-compose.yml up postgres`.

I think it's worth mentioning that the user can skip step 3 if they have a local instance of postgreSQL, and update `.env` accordingly.

2023-07-05 11:51 UTC, andrablaj approved these changes
:shipit:

2023-07-05 11:51 UTC, andrablaj commented on env.template
> +DBT_POSTGRES_HOST=postgres # Your postgres instance IPA or endpoint in "prod".
```suggestion
DBT_POSTGRES_HOST=postgres # Your postgres instance IP or endpoint in "prod".
```

2023-07-05 18:02 UTC, merged